apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: efaflxotz-go 
  janus-idp.io/tekton: efaflxotz-go
  backstage.io/kubernetes-id: efaflxotz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: efaflxotz-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  