apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: efaflxotz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:064297e0a286b1ff6670a010eb6ada6dc3cfa963@sha256:ce0415a2a5b3893a44ed0a1de1f87f553409b8dfa443cd85c80a67ead6907d66
          name: container-image
